  master1:
    #image: sequenceiq/hadoop-docker:latest
    build: .
    hostname: master1
    volumes:
      - /usr/local/hadoop/master1:/usr/local/hadoop/tmp
    external_links:
      - slave1
      - slave2
  slave1:
    build: ../slave1
    hostname: slave1
    volumes:
       - /usr/local/hadoop/slave1:/usr/local/hadoop/tmp
  slave2:
    build: ../slave2
    hostname: slave2
    volumes:
      - /usr/local/hadoop/slave2:/usr/local/hadoop/tmp
